version: '2.1'

services:
  db:
    image: postgres
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  web:
    build: .
    command: sh runserver.sh
    volumes:
      - .:/code
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/restapi?user=admin&password=asdf1234"
      PSQL_URL: "jdbc:postgresql://db:5432/restapi"
    ports:
      - "9000:9000"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy