version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    command: ["./wait-for-it.sh", "db/5432", "/code/runserver.sh"]
    volumes:
      - .:/code
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/restapi?user=admin&password=asdf1234"
      PSQL_URL: "jdbc:postgresql://db:5432/restapi"
    ports:
      - "9000:9000"
    links:
      - db